// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SavePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePageRequest) Reset() {
	*x = SavePageRequest{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePageRequest) ProtoMessage() {}

func (x *SavePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePageRequest.ProtoReflect.Descriptor instead.
func (*SavePageRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *SavePageRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type SavePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PageId        string                 `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePageResponse) Reset() {
	*x = SavePageResponse{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePageResponse) ProtoMessage() {}

func (x *SavePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePageResponse.ProtoReflect.Descriptor instead.
func (*SavePageResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *SavePageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SavePageResponse) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *SavePageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPageRequest) Reset() {
	*x = CheckPageRequest{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPageRequest) ProtoMessage() {}

func (x *CheckPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPageRequest.ProtoReflect.Descriptor instead.
func (*CheckPageRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *CheckPageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CheckPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	PageId        string                 `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPageResponse) Reset() {
	*x = CheckPageResponse{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPageResponse) ProtoMessage() {}

func (x *CheckPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPageResponse.ProtoReflect.Descriptor instead.
func (*CheckPageResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *CheckPageResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckPageResponse) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type GetPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	PageId        string                 `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageRequest) Reset() {
	*x = GetPageRequest{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageRequest) ProtoMessage() {}

func (x *GetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageRequest.ProtoReflect.Descriptor instead.
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *GetPageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetPageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type GetPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageResponse) Reset() {
	*x = GetPageResponse{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageResponse) ProtoMessage() {}

func (x *GetPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageResponse.ProtoReflect.Descriptor instead.
func (*GetPageResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *GetPageResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *GetPageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SaveLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLinkRequest) Reset() {
	*x = SaveLinkRequest{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLinkRequest) ProtoMessage() {}

func (x *SaveLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLinkRequest.ProtoReflect.Descriptor instead.
func (*SaveLinkRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

func (x *SaveLinkRequest) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type SaveLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LinkId        string                 `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLinkResponse) Reset() {
	*x = SaveLinkResponse{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLinkResponse) ProtoMessage() {}

func (x *SaveLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLinkResponse.ProtoReflect.Descriptor instead.
func (*SaveLinkResponse) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *SaveLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveLinkResponse) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	ContentText   string                 `protobuf:"bytes,6,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"`
	Depth         int32                  `protobuf:"varint,7,opt,name=depth,proto3" json:"depth,omitempty"`
	IsProcessed   bool                   `protobuf:"varint,8,opt,name=is_processed,json=isProcessed,proto3" json:"is_processed,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	VisitedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=visited_at,json=visitedAt,proto3" json:"visited_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *Page) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Page) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Page) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Page) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *Page) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Page) GetIsProcessed() bool {
	if x != nil {
		return x.IsProcessed
	}
	return false
}

func (x *Page) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Page) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Page) GetVisitedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VisitedAt
	}
	return nil
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromPageId    string                 `protobuf:"bytes,2,opt,name=from_page_id,json=fromPageId,proto3" json:"from_page_id,omitempty"`
	ToPageUrl     string                 `protobuf:"bytes,3,opt,name=to_page_url,json=toPageUrl,proto3" json:"to_page_url,omitempty"`
	AnchorText    string                 `protobuf:"bytes,4,opt,name=anchor_text,json=anchorText,proto3" json:"anchor_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{9}
}

func (x *Link) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Link) GetFromPageId() string {
	if x != nil {
		return x.FromPageId
	}
	return ""
}

func (x *Link) GetToPageUrl() string {
	if x != nil {
		return x.ToPageUrl
	}
	return ""
}

func (x *Link) GetAnchorText() string {
	if x != nil {
		return x.AnchorText
	}
	return ""
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\astorage\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\x0fSavePageRequest\x12!\n" +
	"\x04page\x18\x01 \x01(\v2\r.storage.PageR\x04page\"_\n" +
	"\x10SavePageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"$\n" +
	"\x10CheckPageRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"D\n" +
	"\x11CheckPageResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageId\";\n" +
	"\x0eGetPageRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageId\"N\n" +
	"\x0fGetPageResponse\x12!\n" +
	"\x04page\x18\x01 \x01(\v2\r.storage.PageR\x04page\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"4\n" +
	"\x0fSaveLinkRequest\x12!\n" +
	"\x04link\x18\x01 \x01(\v2\r.storage.LinkR\x04link\"E\n" +
	"\x10SaveLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\alink_id\x18\x02 \x01(\tR\x06linkId\"\x84\x03\n" +
	"\x04Page\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12!\n" +
	"\fcontent_text\x18\x06 \x01(\tR\vcontentText\x12\x14\n" +
	"\x05depth\x18\a \x01(\x05R\x05depth\x12!\n" +
	"\fis_processed\x18\b \x01(\bR\visProcessed\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"visited_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tvisitedAt\"y\n" +
	"\x04Link\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\ffrom_page_id\x18\x02 \x01(\tR\n" +
	"fromPageId\x12\x1e\n" +
	"\vto_page_url\x18\x03 \x01(\tR\ttoPageUrl\x12\x1f\n" +
	"\vanchor_text\x18\x04 \x01(\tR\n" +
	"anchorText2\x9a\x02\n" +
	"\x0eStorageService\x12?\n" +
	"\bSavePage\x12\x18.storage.SavePageRequest\x1a\x19.storage.SavePageResponse\x12H\n" +
	"\x0fCheckPageExists\x12\x19.storage.CheckPageRequest\x1a\x1a.storage.CheckPageResponse\x12<\n" +
	"\aGetPage\x12\x17.storage.GetPageRequest\x1a\x18.storage.GetPageResponse\x12?\n" +
	"\bSaveLink\x12\x18.storage.SaveLinkRequest\x1a\x19.storage.SaveLinkResponseB\vZ\t.;storageb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_storage_proto_goTypes = []any{
	(*SavePageRequest)(nil),       // 0: storage.SavePageRequest
	(*SavePageResponse)(nil),      // 1: storage.SavePageResponse
	(*CheckPageRequest)(nil),      // 2: storage.CheckPageRequest
	(*CheckPageResponse)(nil),     // 3: storage.CheckPageResponse
	(*GetPageRequest)(nil),        // 4: storage.GetPageRequest
	(*GetPageResponse)(nil),       // 5: storage.GetPageResponse
	(*SaveLinkRequest)(nil),       // 6: storage.SaveLinkRequest
	(*SaveLinkResponse)(nil),      // 7: storage.SaveLinkResponse
	(*Page)(nil),                  // 8: storage.Page
	(*Link)(nil),                  // 9: storage.Link
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_storage_proto_depIdxs = []int32{
	8,  // 0: storage.SavePageRequest.page:type_name -> storage.Page
	8,  // 1: storage.GetPageResponse.page:type_name -> storage.Page
	9,  // 2: storage.SaveLinkRequest.link:type_name -> storage.Link
	10, // 3: storage.Page.created_at:type_name -> google.protobuf.Timestamp
	10, // 4: storage.Page.updated_at:type_name -> google.protobuf.Timestamp
	10, // 5: storage.Page.visited_at:type_name -> google.protobuf.Timestamp
	0,  // 6: storage.StorageService.SavePage:input_type -> storage.SavePageRequest
	2,  // 7: storage.StorageService.CheckPageExists:input_type -> storage.CheckPageRequest
	4,  // 8: storage.StorageService.GetPage:input_type -> storage.GetPageRequest
	6,  // 9: storage.StorageService.SaveLink:input_type -> storage.SaveLinkRequest
	1,  // 10: storage.StorageService.SavePage:output_type -> storage.SavePageResponse
	3,  // 11: storage.StorageService.CheckPageExists:output_type -> storage.CheckPageResponse
	5,  // 12: storage.StorageService.GetPage:output_type -> storage.GetPageResponse
	7,  // 13: storage.StorageService.SaveLink:output_type -> storage.SaveLinkResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
